
from sqlalchemy import Column, Integer, String, Text, Boolean, ForeignKey, Float, DateTime, JSON
from sqlalchemy.orm import relationship
from app.core.database import Base

class Question(Base):
    __tablename__ = 'questions'
    id = Column(Integer, primary_key=True)
    assessment_id = Column(Integer, ForeignKey('assessments.id'))
    topic_id = Column(Integer, ForeignKey('topics.id'))
    subtopic_id = Column(Integer, ForeignKey('subtopics.id'))
    text = Column(Text)
    marks = Column(Integer)
    difficulty = Column(String)
    explanation = Column(Text)

class QuestionOption(Base):
    __tablename__ = 'question_options'
    id = Column(Integer, primary_key=True)
    question_id = Column(Integer, ForeignKey('questions.id'))
    text = Column(Text)
    is_correct = Column(Boolean)

class SkillGapReport(Base):
    """
    Stores Skill Gap Analysis reports generated by the agent.

    Each report represents one complete analysis of a student's attempt,
    including personalized recommendations and learning guidance.
    """
    __tablename__ = 'skill_gap_reports'
    id = Column(Integer, primary_key=True)
    student_id = Column(Integer, ForeignKey('students.id'), nullable=False, index=True)
    attempt_id = Column(Integer, ForeignKey('attempts.id'), nullable=False, unique=True, index=True)
    level_id = Column(Integer, ForeignKey('levels.id'), nullable=False)
    created_at = Column(DateTime, nullable=False)

    # Overall summary and assessment
    summary = Column(Text)
    overall_performance = Column(Text)

    # Recommendations and study plan
    recommendations = Column(JSON)  # List of recommendation dicts
    study_plan = Column(JSON)  # List of study plan items

    # Next level readiness
    next_level_readiness = Column(String)  # READY, NEEDS_TARGETED_PREPARATION, etc.
    next_level_id = Column(Integer, ForeignKey('levels.id'), nullable=True)

    # Adaptive assessment strategy
    adaptive_assessment_plan = Column(JSON)  # Strategy for next assessment

    # Confidence and metadata
    confidence = Column(String)  # HIGH, MEDIUM, LOW
    confidence_factors = Column(JSON)  # List of factor strings
    evidence_quality = Column(Text)

    # Analysis version for schema evolution
    analysis_version = Column(String, default='1.0')

    # LLM interpretation (optional - may be None if LLM unavailable)
    llm_interpretation = Column(Text, nullable=True)

class SkillGapItem(Base):
    """
    Stores individual skill gap items (weaknesses) identified in a report.

    Each item represents one topic/subtopic where the student needs improvement,
    with evidence, classification, and specific recommendations.
    """
    __tablename__ = 'skill_gap_items'
    id = Column(Integer, primary_key=True)
    report_id = Column(Integer, ForeignKey('skill_gap_reports.id'), nullable=False, index=True)
    topic_id = Column(Integer, ForeignKey('topics.id'), nullable=False)
    subtopic_id = Column(Integer, ForeignKey('subtopics.id'), nullable=True)

    # Topic identification
    topic_name = Column(String)
    subtopic_name = Column(String, nullable=True)

    # Performance data
    accuracy = Column(Float)  # 0.0-1.0 fraction

    # Classification and analysis
    severity = Column(String)  # HIGH, MEDIUM, LOW
    priority = Column(Integer)  # 1=highest priority
    classification = Column(String)  # PERSISTENT, CURRENT, IMPROVING
    trend = Column(String, nullable=True)  # IMPROVING, STABLE, DECLINING, VOLATILE, INSUFFICIENT_DATA

    # Evidence and reasoning
    evidence = Column(Text)
    reason = Column(Text)
    recommended_action = Column(Text)

    # Confidence
    confidence = Column(String)  # HIGH, MEDIUM, LOW
